### ISSUE TITLE
Ort information cut on the right screen side

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app#12]
![Screenshot_20190617-190644](https://user-images.githubusercontent.com/1942953/59622996-5b24aa80-9133-11e9-8bcb-bfd3f59548a0.png)

**Comment by SoleCincis** [comment]
issue solved with line break after street . 
TODO: add a logic to display category and url in a way that fit the screen even when is long text (not jet a problem because there are no POI with long text at the moment)

**Comment by donni106** [comment]
@SoleCincis can you provide a screen shot of your solution? Is the solution already available for users?

**Comment by SoleCincis** [comment]
yes and yes . where should I post the screen shot , here ?
