### ISSUE TITLE
Sharing Links - Inhalt fehlt

### ISSUE THREAD

**Issue by marcometz** [ikuseiGmbH/smart-village-app#13]
die SharingLinks bei Veranstaltung, PoI und Touren haben keine Inhalte.
Dies sollte vermutlich ähnlich sein zum SharingLink bei News

**Comment by donni106** [comment]
Bei Veranstaltungen und Nachrichten sehe ich Sharing-Inhalte.
Bei Orten und Touren sind sie `undefined`.

**Comment by donni106** [comment]
Will be fixed in 0.9.0 with https://github.com/ikuseiGmbH/smart-village-app-app/pull/29/commits/016266381b04318d401098665668eb2be7bd492f
