### ISSUE TITLE
Swipe left to go "back"

### ISSUE THREAD

**Issue by marcometz** [ikuseiGmbH/smart-village-app#8]
It would be nice to swipe left to go previous screen

**Comment by donni106** [comment]
it is working already for every stack navigation process.
you can swipe back in every screen where a "back" action is possible. you can recognize that on the "<" element on the top left in the header bar.
when navigating in the drawer, you are navigating in the same layer. there is no stack to go back and forth.

**Comment by marcometz** [comment]
Works now.
